apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkinns-deploy
spec:
  replicas: 3
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: tomjen
    spec:
      containers:
      - name: tomjen
        image: bpraveen18/tomjen
        ports:
        - containerPort: 8080
